"""Versioned critical/high threat inventory bound to hostile pytest nodes."""

from __future__ import annotations

from cortheon.threat_model.catalog_release import (
    RELEASE_RESIDUALS,
    RELEASE_RISK_IDS,
    RELEASE_RISKS,
)
from cortheon.threat_model.models import (
    MODEL_VERSION,
    SCHEMA_VERSION,
    ResidualRisk,
    ThreatManifest,
    ThreatRisk,
)


def _risk(
    risk_id: str,
    severity: str,
    phase: str,
    attack: str,
    *nodes: str,
) -> ThreatRisk:
    return ThreatRisk(
        risk_id,
        severity,  # type: ignore[arg-type]
        phase,
        PHASE_OWNERS[phase],
        attack,
        tuple(nodes),
    )


PHASE_OWNERS = {
    "lifecycle": "runtime_lifecycle",
    "prompt_injection": "evidence_integrity",
    "evidence": "evidence_integrity",
    "receipts": "execution_receipts",
    "test_integrity": "benchmark_integrity",
    "sandbox": "sandbox_safety",
    "concurrency": "host_integrations",
    "transport": "transport_safety",
    "measurement": "measurement_integrity",
    "model_identity": "model_identity",
    "packaging": "release_engineering",
    "private_pack": "privacy_boundary",
}


REQUIRED_RISK_IDS = (
    "runaway_reasoning_loop",
    "degraded_session_reuse",
    "stale_observation_replay",
    "terminal_verdict_laundering",
    "repair_prompt_injection",
    "web_instruction_injection",
    "poisoned_required_source",
    "mixed_origin_source_fraud",
    "semantic_source_binding_fraud",
    "execution_identity_spoof",
    "receipt_session_spoof",
    "missing_receipt_export",
    "patch_test_tampering",
    "repository_path_escape",
    "secret_bearing_file_read",
    "unsafe_host_command",
    "runtime_start_race",
    "control_channel_cross_read",
    "policy_rejection_false_allow",
    "abandon_transport_laundering",
    "unterminated_stream_timeout",
    "duplicate_pair_overwrite",
    "stale_measurement_summary",
    "diagnostic_grader_promotion",
    "abort_envelope_spoof",
    "observed_model_mismatch",
    "unrequested_export_model",
    "distribution_allowlist_drift",
    "unpinned_adapter_source",
    "plugin_cache_dependency_leak",
    "private_oracle_label_leak",
    "blind_prompt_pack_leak",
    "qualification_repository_path_leak",
    "generic_terminal_transcript_forgery",
    "generic_model_identity_spoof",
    "generic_model_cost_spoof",
    "generic_control_fd_isolation_failure",
    "generic_web_provider_mutation",
    "generic_sigterm_cleanup_failure",
    "frozen_archive_membership_attack",
    "frozen_current_import_poisoning",
    "frozen_artifact_mutation",
    "designated_host_condition_leakage",
    *RELEASE_RISK_IDS,
)

RISKS = (
    _risk(
        "runaway_reasoning_loop",
        "critical",
        "lifecycle",
        "A hostile model can keep the host in an unbounded reasoning/tool loop.",
        "tests/test_pi_doom_loop.py::test_hostile_model_never_complies_still_exits",
    ),
    _risk(
        "degraded_session_reuse",
        "high",
        "lifecycle",
        "Repeated runtime failures can leave a poisoned host session active.",
        "tests/test_cognitive_hooks_lifecycle.py::test_hook_tracker_degrades_a_host_session_after_repeated_failures",
    ),
    _risk(
        "stale_observation_replay",
        "critical",
        "lifecycle",
        "A stale duplicate observation can overwrite current session evidence.",
        "tests/test_pi_observe_claim.py::test_stale_duplicate_response_cannot_overwrite_the_session",
    ),
    _risk(
        "terminal_verdict_laundering",
        "critical",
        "lifecycle",
        "Host output can bypass or rewrite an evaluator-sealed terminal verdict.",
        "tests/test_pi_lifecycle_withheld.py::test_terminal_block_uses_the_evaluator_sealed_verdict",
    ),
    _risk(
        "repair_prompt_injection",
        "critical",
        "prompt_injection",
        "Injected repair evidence can become the final answer.",
        "tests/test_pi_causal_synthesis.py::test_prompt_injection_repair_can_never_become_the_answer",
    ),
    _risk(
        "web_instruction_injection",
        "high",
        "prompt_injection",
        "Instruction-shaped web content can escape evidence quarantine.",
        "tests/test_pi_web_evidence.py::test_instruction_shaped_web_payload_stays_verbatim_for_quarantine",
    ),
    _risk(
        "poisoned_required_source",
        "critical",
        "evidence",
        "A poisoned mandatory source can still certify synthesis.",
        "tests/test_pi_synthesis_operator.py::test_poisoned_required_read_withholds_everywhere",
    ),
    _risk(
        "mixed_origin_source_fraud",
        "critical",
        "evidence",
        "One fetch can falsely combine evidence from multiple origins.",
        "tests/test_pi_web_evidence.py::test_fetch_rejects_mixed_structured_origins",
    ),
    _risk(
        "semantic_source_binding_fraud",
        "critical",
        "evidence",
        "Direction, polarity, quantity, or source swaps can pass a semantic oracle.",
        "tests/test_north_star_oracles_graphs.py::test_semantic_documents_reject_direction_polarity_quantity_and_source_swaps",
    ),
    _risk(
        "execution_identity_spoof",
        "critical",
        "receipts",
        "Tool or content fields can spoof host execution identity.",
        "tests/test_execution_provenance.py::test_tool_or_content_spoofs_cannot_supply_execution_identity",
    ),
    _risk(
        "receipt_session_spoof",
        "critical",
        "receipts",
        "Nested or mixed session identifiers can forge an execution receipt.",
        "tests/test_opencode_execution_receipt.py::test_session_id_rejects_nested_spoof_and_top_level_mix",
    ),
    _risk(
        "missing_receipt_export",
        "critical",
        "receipts",
        "A run can promote without its sanitized host receipt.",
        "tests/test_opencode_execution_receipt.py::test_run_job_fails_closed_when_sanitized_export_is_missing",
    ),
    _risk(
        "patch_test_tampering",
        "critical",
        "test_integrity",
        "A candidate can edit tests instead of satisfying the patch oracle.",
        "tests/test_north_star_oracles_research.py::test_patch_grader_rejects_a_direct_test_tampering_diff_before_execution",
    ),
    _risk(
        "repository_path_escape",
        "critical",
        "sandbox",
        "Repository reads can traverse outside the authorized root.",
        "tests/test_generic_mcp_interception.py::test_executor_rejects_repository_escape",
    ),
    _risk(
        "secret_bearing_file_read",
        "critical",
        "sandbox",
        "Evaluator tools can expose protected control material.",
        "tests/test_generic_mcp_interception.py::test_executor_rejects_protected_control_file_reads",
    ),
    _risk(
        "unsafe_host_command",
        "critical",
        "sandbox",
        "The adapter can execute a command outside the scheduled safe command set.",
        "tests/test_cognitive_hooks_codex_adapter.py::test_codex_host_adapter_accepts_only_scheduled_diff_and_test_commands",
    ),
    _risk(
        "runtime_start_race",
        "high",
        "concurrency",
        "Concurrent starts can create multiple runtime owners.",
        "tests/test_codex_runtime_and_web.py::test_concurrent_runtime_start_has_one_process_owner",
    ),
    _risk(
        "control_channel_cross_read",
        "critical",
        "concurrency",
        "Concurrent evaluators can cross-read private control payloads.",
        "tests/test_evaluator_control_fd.py::test_concurrent_processes_cannot_cross_read_control_payloads",
    ),
    _risk(
        "policy_rejection_false_allow",
        "critical",
        "transport",
        "A policy rejection can fail open instead of withholding.",
        "tests/test_pi_completion_transport.py::test_policy_422_fails_closed_with_one_withhold_and_abandon",
    ),
    _risk(
        "abandon_transport_laundering",
        "critical",
        "transport",
        "An abandon transport failure can launder a blocked answer.",
        "tests/test_pi_lifecycle_withheld.py::test_abandon_transport_failure_does_not_launder_the_block",
    ),
    _risk(
        "unterminated_stream_timeout",
        "high",
        "transport",
        "An unterminated stream chunk can defeat the evaluator timeout.",
        "tests/test_execution_provenance.py::test_streaming_timeout_cannot_be_blocked_by_an_unterminated_chunk[1]",
        "tests/test_execution_provenance.py::test_streaming_timeout_cannot_be_blocked_by_an_unterminated_chunk[2]",
    ),
    _risk(
        "duplicate_pair_overwrite",
        "critical",
        "measurement",
        "Duplicate comparison cells can overwrite outcomes order-dependently.",
        "tests/test_proof_pairing_integrity.py::test_duplicate_pair_cells_fail_closed_without_order_dependent_overwrite",
    ),
    _risk(
        "stale_measurement_summary",
        "critical",
        "measurement",
        "A stale paired summary can contradict underlying attested rows.",
        "tests/test_parity_report_metrics.py::test_stale_paired_comparison_cannot_contradict_attested_rows",
    ),
    _risk(
        "diagnostic_grader_promotion",
        "critical",
        "measurement",
        "A diagnostic-only grader can be relabelled proof-eligible.",
        "tests/test_parity_report_metrics.py::test_diagnostic_grader_cannot_be_relabelled_as_proof_eligible",
    ),
    _risk(
        "abort_envelope_spoof",
        "high",
        "measurement",
        "Near-match abort envelopes can disappear from the measured denominator.",
        "tests/test_pi_abort_measurement.py::test_only_one_immediately_adjacent_exact_abort_is_ignored",
    ),
    _risk(
        "observed_model_mismatch",
        "critical",
        "model_identity",
        "A run can claim a different model than the host observed.",
        "tests/test_execution_provenance.py::test_run_job_rejects_a_host_observed_model_mismatch",
    ),
    _risk(
        "unrequested_export_model",
        "critical",
        "model_identity",
        "A consistent receipt for an unrequested model can be accepted.",
        "tests/test_opencode_execution_receipt.py::test_run_job_rejects_a_consistent_but_unrequested_export_model",
    ),
    _risk(
        "distribution_allowlist_drift",
        "critical",
        "packaging",
        "The source archive can ship files outside the reviewed runtime allowlist.",
        "tests/test_lightweight_distribution.py::test_source_archive_uses_the_same_runtime_allowlist",
    ),
    _risk(
        "unpinned_adapter_source",
        "critical",
        "packaging",
        "Changed adapter source can ship without updating its reviewed pin.",
        "tests/test_pi_architecture.py::test_changed_source_without_hash_update_fails_closed",
    ),
    _risk(
        "plugin_cache_dependency_leak",
        "high",
        "packaging",
        "A cached hook can depend on a Cortheon package absent from the host.",
        "tests/test_codex_hook_packaging.py::test_cache_copied_wheel_hook_needs_no_cortheon_package_at_all[wheel]",
        "tests/test_codex_hook_packaging.py::test_cache_copied_wheel_hook_needs_no_cortheon_package_at_all[sdist_wheel]",
    ),
    _risk(
        "private_oracle_label_leak",
        "critical",
        "private_pack",
        "Public case projections can expose private oracle labels or hints.",
        "tests/test_north_star_oracles_research.py::test_public_projection_contains_no_private_oracle_labels_or_hints",
    ),
    _risk(
        "blind_prompt_pack_leak",
        "critical",
        "private_pack",
        "A contender prompt can reveal the private benchmark pack or workspace.",
        "tests/test_frontier_benchmark.py::test_frontier_command_is_ephemeral_blind_and_prompt_bounded",
    ),
    _risk(
        "qualification_repository_path_leak",
        "high",
        "private_pack",
        "Qualification output can disclose the private repository path.",
        "tests/test_qualification_cli.py::test_validate_only_is_machine_readable_and_has_no_repository_path",
    ),
    _risk(
        "generic_terminal_transcript_forgery",
        "critical",
        "receipts",
        "Model-authored terminal JSON or events appended after terminal can forge the evaluator transcript.",
        "tests/test_generic_mcp_interception.py::test_raw_model_terminal_json_never_becomes_an_envelope",
        "tests/test_generic_mcp_interception.py::test_transcript_rejects_events_after_terminal",
    ),
    _risk(
        "generic_model_identity_spoof",
        "critical",
        "model_identity",
        "Malformed identities, false capabilities, or transcript identity mutation can spoof the evaluated model.",
        "tests/test_generic_mcp_interception.py::test_claim_validator_rejects_closed_schema_identity_and_terminal_tampering",
        "tests/test_generic_mcp_hardening.py::test_validator_rejects_unbounded_identity_calls_and_false_capabilities",
    ),
    _risk(
        "generic_model_cost_spoof",
        "high",
        "measurement",
        "Coercible booleans or strings can masquerade as evaluator-observed model cost.",
        "tests/test_generic_mcp_hardening.py::test_model_cost_rejects_coercible_non_numbers[True]",
        "tests/test_generic_mcp_hardening.py::test_model_cost_rejects_coercible_non_numbers[0.01]",
    ),
    _risk(
        "generic_control_fd_isolation_failure",
        "critical",
        "private_pack",
        "The model or its tool shell can recover evaluator-only control data or own the terminal channel.",
        "tests/test_generic_mcp_process.py::test_child_reads_control_fd_and_owns_the_only_terminal",
        "tests/test_evaluator_control_fd.py::test_tool_shell_cannot_recover_payload_from_parent_launch_or_fd[./src/cortheon/pi_core/protocol.ts-pi-True]",
        "tests/test_evaluator_control_fd.py::test_tool_shell_cannot_recover_payload_from_parent_launch_or_fd[./src/cortheon/opencode_core/state.js-opencode-False]",
    ),
    _risk(
        "generic_web_provider_mutation",
        "critical",
        "evidence",
        "A web provider executable, redirect target, or identity digest can change after capability binding.",
        "tests/test_generic_mcp_hardening.py::test_web_provider_executes_resolved_hashed_path_and_detects_change",
        "tests/test_generic_mcp_web.py::test_web_fetch_rejects_redirected_source_and_bad_provider_digest",
    ),
    _risk(
        "generic_sigterm_cleanup_failure",
        "critical",
        "lifecycle",
        "SIGTERM during a blocked model call can leave the runtime active or produce a claim-eligible terminal.",
        "tests/test_generic_mcp_process.py::test_sigterm_during_blocked_model_call_closes_runtime_and_fails_claim",
    ),
    _risk(
        "frozen_archive_membership_attack",
        "critical",
        "packaging",
        "Duplicate, traversal-shaped, or unexpected frozen archive members can bypass the closed member set.",
        "tests/test_frozen_old_planner.py::test_archive_duplicate_member_fails_before_extraction",
    ),
    _risk(
        "frozen_current_import_poisoning",
        "critical",
        "test_integrity",
        "The historical comparator can import current repository code instead of its extracted frozen program.",
        "tests/test_frozen_old_planner.py::test_verified_runtime_imports_only_the_extracted_program",
    ),
    _risk(
        "frozen_artifact_mutation",
        "critical",
        "test_integrity",
        "A mutated frozen archive, wrapper, member, or smoke receipt can be accepted as the historical artifact.",
        "tests/test_frozen_old_planner.py::test_archive_and_smoke_receipt_are_content_addressed",
    ),
    _risk(
        "designated_host_condition_leakage",
        "critical",
        "measurement",
        "Historical-condition rows can leak into a non-designated host or be replaced by a spoofed condition.",
        "tests/test_qualification_report.py::test_historical_contrast_uses_only_designated_opencode_cells",
        "tests/test_frozen_old_planner.py::test_historical_manifest_is_explicit_and_opencode_only",
        "tests/test_frozen_old_planner.py::test_historical_manifest_rejects_spoofed_or_missing_condition",
    ),
    *RELEASE_RISKS,
)

RESIDUALS = (
    ResidualRisk(
        "deployment_configuration_drift",
        "medium",
        "Repository tests cannot prove every downstream host deployment preserves the reviewed configuration.",
        "Require host-specific conformance evidence before release promotion.",
    ),
    ResidualRisk(
        "semantic_test_weakening",
        "medium",
        "File digests expose test changes but cannot determine whether a reviewer-approved change weakened the assertion.",
        "Two independent reviewers must inspect exact report bytes and changed test sources.",
    ),
    ResidualRisk(
        "unsigned_local_report",
        "medium",
        "This repository does not contain trusted reviewer keys or a signature verifier.",
        "Promotion remains false until an external verifier authenticates both signoffs.",
    ),
    ResidualRisk(
        "unknown_attack_classes",
        "low",
        "A fixed catalog cannot prove that no new attack class exists.",
        "Version the catalog and repeat hostile review when architecture or threat intelligence changes.",
    ),
    *RELEASE_RESIDUALS,
)

THREAT_MANIFEST = ThreatManifest(SCHEMA_VERSION, MODEL_VERSION, RISKS, RESIDUALS)
